### ISSUE TITLE
GUID custom scalar produces unknown Typescript Type

### ISSUE THREAD

**Issue by tadejstanic** [danielrearden/sqlmancer#77] opened 2020-05-29 13:19 UTC
I have this graphql schema definition: 

```
scalar GUID

type User @model(table: "user", pk: "id") {
  id: GUID!
  firstName: String!
  lastName: String
}

type Query @sqlmancer(dialect: POSTGRES, customScalars: { string: ["GUID"] }) {
  userById(id: GUID!): User
}
```

But when I run `sqlmancer generate` I get some types with 'unknown' value:

```
export type UserIds = unknown;
    
export type UserEnums = unknown;
```

Because of this, I get a TSerror:

![image](https://user-images.githubusercontent.com/7260332/83263724-54b20600-a1bf-11ea-9d4b-8219e8e850bd.png)

`Type 'unknown' does not satisfy the constraint 'string'.`

From my understanding, shouldn't `unknown` be a type of `string[]`?

**Comment by danielrearden** [comment] 2020-05-29 16:04
Thanks for the bug report. Should be fixed now with v0.3.1. Please let me know if you come across any other issues!

**Comment by tadejstanic** [comment] 2020-05-30 10:52
Thanks for the fix. However, it doesn't work for my case. It still produces the `unknown` type.

**Comment by danielrearden** [comment] 2020-05-30 12:33
@tadejstanic  The typing is correct. It's only used internally to help type the result returned when calling `execute` on the builder instance. It doesn't actually reflect the type of your specific `id` field. You've specified the GUID scalar is a string in your configuration, so the `id` field should be typed as a `string` when returned as a result or provided as as input.

For context, that type variable keeps track of any fields using the built-in `ID` type so those fields specifically can be typed correctly.

I'll reopen the issue. If the `unknown` typing is still causing a compiler error, the `id` field isn't being typed as a `string` or if you're hitting some other issue, let me know. Otherwise, we'll close this as "working as intended".

**Closed** 2020-06-07 16:08 UTC
Labels: bug
